{{- if .Values.tei.reranker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hindsight.fullname" . }}-tei-reranker
  labels:
    {{- include "hindsight.tei.reranker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.tei.reranker.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "hindsight.tei.reranker.selectorLabels" . | nindent 4 }}
{{- end }}
